### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by suburbanbourbon** [x0wllaar/MPV-SMTC#1]
Hey! I recently stumbled upon this MPV plugin. And I like it and have been using it ever since.

I am intrigued to know if this project has been abandoned or if you are busy. I would have contributed to this project myself, but I know neither C# nor Lua.

And you should register your project over here if you want to: https://github.com/mpv-player/mpv/wiki/User-Scripts.

Another thing, this project was able to solve the thumbnail issue https://github.com/datasone/MPVMediaControl however that project has some problems of its own.

**Comment by Tosh0kan** [comment]
Project status: Dead af

**Comment by x0wllaar** [comment]
> Project status: Dead af

Pretty much this. With the advent of Windows 11 (and its policies towards everything, including but not limited to the hardware reqs), I have migrated way from Windows as my main OS. The project will still work for Windows 10, but I had problems running it on Windows 11. That said, probably you can get it to work if you actually have Windows :)

I won't remove this repository because the project still works, but I think I'll archive it in the near future

**Comment by Tosh0kan** [comment]
In that case, why not continue to exclusively developing for Win 10

**Comment by NaiveInvestigator** [comment]
The other project has made some improvements, @Tosh0kan  I think you should check it out. Send PRs over there if you find issues.

**Comment by Tosh0kan** [comment]
@NaiveInvestigator What other project?

**Comment by suburbanbourbon** [comment]
@Tosh0kan https://github.com/datasone/MPVMediaControl

**Comment by xathian** [comment]
Super disappointing to hear. There other 2 alternatives people always suggest work no where near as well for me. One requires running a background program that sits in the system tray 24/7 to work and the other doesn't work reliably at all. This one however worked (and continues to work) flawlessly.
